version: '3.9'

services:
  crudfastapi:
    build: .
    env_file:
      - .env
    command: bash -c "
      uvicorn app.app:app
      --host 0.0.0.0 --port 8989
      --reload
      "
    volumes:
      - .:/app
    ports:
      - "8989:8989"
    depends_on:
      - mongodb

  mongodb:
    image: mongo
    env_file:
      - .env
    ports:
      - "27017:27017"
    environment:
      - "MONGO_INITDB_DATABASE=${MONGO_DB}"
      - "MONGO_INITDB_ROOT_USERNAME=${MONGO_USER}"
      - "MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASS}"